PROJECT_DIR=$(dirname "$(dirname "$(pwd)")")
EXEPATH="$PROJECT_DIR/bin"
CERT_PATH="$PROJECT_DIR/scripts/certificates"

MATTER_DAC_LOC=0xE0E0
MATTER_PAI_LOC=0xE0E8
MATTER_CD_LOC=0xF1E0

DEFAULT_SEC_CONFIG="000050100000000"
DEFAULT_METADATA=""

MATTER_DAC_TAG="_E0E0.pem"
MATTER_PAI_TAG="PAI-noPID-Cert.pem"
MATTER_CD_TAG="CD-Cert.bin"